const regionFromCrnMask = {
  "au-syd": "Sydney",
  "br-sao": "Sao Paulo",
  "ca-mon": "ca-mon",
  "ca-tor": "Toronto",
  "eu-de": "Frankfurt",
  "eu-es": "Madrid",
  "eu-fr2": "Bnpp",
  "eu-gb": "London",
  "in-che": "Chennai",
  "jp-osa": "Osaka",
  "jp-tok": "Tokyo",
  "us-east": "Washington DC",
  "us-south-ngdc-test": "Dallas-ngdc-test",
  "us-south": "Dallas",
  "wdc06-pvs-01": "Washington DC",
  ams02: "Amsterdam",
  ams03: "Amsterdam",
  atl01: "Atlanta",
  che01: "Chennai",
  dal03: "Dallas",
  dal05: "Dallas",
  dal09: "Dallas",
  dal10: "Dallas",
  dal12: "Dallas",
  dal13: "Dallas",
  dal14: "Dallas",
  den01: "Denver",
  fra02: "Frankfurt",
  fra04: "Frankfurt",
  fra05: "Frankfurt",
  hkg01: "Hong Kong",
  hkg03: "Hong Kong",
  lon02: "London",
  lon03: "London",
  lon04: "London",
  lon05: "London",
  lon06: "London",
  mad02: "Madrid",
  mad04: "Madrid",
  mad05: "Madrid",
  mia01: "Miami",
  mil01: "Milan",
  mon01: "Montreal",
  mon02: "Montreal",
  mon04: "Montreal",
  mum01: "Mumbai",
  osa01: "Osaka",
  osa21: "Osaka",
  osa22: "Osaka",
  osa23: "Osaka",
  other: "Other",
  par01: "Paris",
  par02: "Paris",
  par04: "Paris",
  par05: "Paris",
  par06: "Paris",
  sao01: "Sao Paulo",
  sao02: "Sao Paulo",
  sao03: "Sao Paulo",
  sao04: "Sao Paulo",
  sao05: "Sao Paulo",
  satellite: "Satellite",
  sea02: "Seattle",
  sjc02: "San Jose",
  sjc03: "San Jose",
  sjc04: "San Jose",
  sng01: "Singapore",
  syd01: "Sydney",
  syd02: "Sydney",
  syd04: "Sydney",
  syd05: "Sydney",
  tok01: "Tokyo",
  tok02: "Tokyo",
  tok04: "Tokyo",
  tok05: "Tokyo",
  tor01: "Toronto",
  tor04: "Toronto",
  tor05: "Toronto",
  wdc02: "Washington DC",
  wdc04: "Washington DC",
  wdc06: "Washington DC",
  wdc07: "Washington DC",
};

const configNames = [
  "backup-recovery",
  "block-storage",
  "cloud-object-storage",
  "compliance",
  "dns-svcs",
  "file-storage",
  "iaas-compute-general",
  "iaas-fabric-classic",
  "iaas-maintenance",
  "iaas-network",
  "iaas-network-infrastructure",
  "ims-fabric",
  "is",
  "is-apis",
  "is-backup-policy",
  "is-bare-metal-server",
  "is-cli",
  "is-cluster-network",
  "is-compute",
  "is-continuous-deploy",
  "is-continuous-integration",
  "is-dedicated-host",
  "is-docker",
  "is-endpoint-gateway",
  "is-fleet",
  "is-floating-ip",
  "is-flow-log-collector",
  "is-genctl",
  "is-genctl-etcd",
  "is-hostos",
  "is-image",
  "is-image-acadia",
  "is-instance",
  "is-instance-group",
  "is-kerberos-kdc",
  "is-key",
  "is-kube",
  "is-load-balancer",
  "is-load-balancer-private-path",
  "is-management-rack",
  "is-metadata",
  "is-network",
  "is-network-acl",
  "is-network-genctl",
  "is-network-ips",
  "is-observability-dashboard",
  "is-observability-datalake",
  "is-observability-logging",
  "is-placement-group",
  "is-platform-integration",
  "is-private-path-service-gateway",
  "is-public-address-range",
  "is-public-gateway",
  "is-publication",
  "is-razee-deploy",
  "is-reservation",
  "is-rias-deploy",
  "is-rias-etcd",
  "is-rias-ingress",
  "is-sdn",
  "is-security-group",
  "is-share",
  "is-snapshot",
  "is-snapshot-consistency-group",
  "is-snapshots-acadia",
  "is-subnet",
  "is-ui",
  "is-vault",
  "is-virtual-network-interface",
  "is-volume",
  "is-volume-acadia",
  "is-vpc",
  "is-vpc-infra",
  "is-vpc-operations",
  "is-vpn",
  "is-vpn-server",
  "is-vulnerability-scan",
  "ngdc-network-underlay",
  "power-iaas",
  "storage-platform-acadia",
  "iaas-compute-monitoring",
  "iaas-compute-provisioning",
  "iaas-cooling",
  "iaas-dc-facilities",
  "iaas-dc-hwsupport",
  "iaas-dc-security",
  "iaas-fabric-ims-core",
  "iaas-fabric-ims-database",
  "iaas-fabric-ims-devauto",
  "iaas-fabric-ims-engine",
  "iaas-fabric-ims-identity",
  "iaas-fabric-op-auth",
  "iaas-fabric-op-cert",
  "iaas-fabric-op-dev-tools",
  "iaas-fabric-op-dns",
  "iaas-firewall-gateway",
  "iaas-internal-systems",
  "iaas-network-oculus",
  "iaas-network-services",
  "iaas-network-subnet-rir",
  "iaas-network-vpn-ipsec",
  "iaas-power"
];


const serviceGroupNames = [
  "Acadia Block and File Storage",
  "Backup and Recovery",
  "Compute - Development",
  "Compute - Operations",
  "COS Storage",
  "Data Center Operations",
  "Fabric",
  "File Block Storage",
  "Network - Overlay",
  "Network - Services",
  "Network - Underlay",
  "Power IaaS",
  "Security Services",
  "Virtual Private Cloud",
  "Virtual Private Cloud - Undercloud",
  "VPC - Platform Services",
  'Network', 
  'Network - Services - verified with security catalog', 
  'IaaS Observability', 
  'Virtual Private Cloud - Security Ops', 
  'Fabric Underlay', 'IBM Cloud for VMware Solutions', 
  'Storage Backup',
  "ITOM-CMDB"
];

const vpMapping = [
  {
    "platform": "storage",
    "serviceGroups": ["Acadia Block and File Storage", "COS Storage", "File Block Storage", "Backup and Recovery"],
    "email":"piyush.shivam@ibm.com",
    "services": [
      'is-image-acadia',
      'is-snapshots-acadia',
      'is-volume-acadia',
      'is-kerberos-kdc',
      'is-backup-policy',
      'is-share',
      'is-snapshot',
      'is-snapshot-consistency-group',
      'is-volume',
      'file-storage',
      'backup-recovery',
      'cloud-object-storage',
      'cloud-object-storage-dedicated',
      'cloud-backup',
      'block-storage',
      'ngdc-fileblock-automation',
      'storage-platform-acadia',
      'cleversafe',
      'object-storage',
      'object-storage-swift-sl',
      'dedicated-storage-cluster',
      'dedicated-storage-instance',
      'vsi-san',
      'compass-network-interconnect'
    ]
  },
  {
    "platform": "compute",
    "serviceGroups": ["Compute - Development", "Compute - Operations"],
    "email":"rajeshr@us.ibm.com",
    "services": [
      'iaas-compute-general',
      'iaas-compute-monitoring',
      'iaas-compute-provisioning',
      'is-bare-metal-server',
      'is-cli',
      'is-compute',
      'is-dedicated-host',
      'is-fleet',
      'is-genctl',
      'is-genctl-etcd',
      'is-hostos',
      'is-image',
      'is-instance',
      'is-instance-group',
      'is-key',
      'is-kube',
      'is-metadata',
      'is-placement-group',
      'is-publication',
      'is-razee-deploy',
      'is-reservation',
      'is-rias-deploy',
      'is-rias-etcd',
      'is-rias-ingress',
      'is-vpc-operations',
      'bare-metal',
      'carbon-calculator',
      'virtual-server',
      'content-image-sppvsnap',
      'vmware',
      'vmware-directorsite',
      'vmware-directorsite-infra-ops',
      'vmware-solutions',
      'vmware-solutions-vcd-shared',
      'vmware-usage-meter',
      'vmware-vdc'
    ]
  },
  {
    "platform": "network",
    "serviceGroups": ["Network - Overlay", "Network - Services", "Network - Underlay"],
    "email":"apoorva.karan@ibm.com",
    "services": [
      'is-apis',
      'is-cluster-network',
      'is-docker',
      'is-network',
      'is-network-acl',
      'is-network-genctl',
      'is-public-address-range',
      'is-sdn',
      'is-virtual-network-interface',
      'is-endpoint-gateway',
      'is-floating-ip',
      'is-load-balancer',
      'is-load-balancer-private-path',
      'is-network-ips',
      'is-private-path-service-gateway',
      'is-public-gateway',
      'is-security-group',
      'is-subnet',
      'is-vpn',
      'is-vpn-server',
      'iaas-firewall-gateway',
      'iaas-network-oculus',
      'iaas-network-vpn-ipsec',
      'iaas-network',
      'iaas-network-infrastructure',
      'iaas-network-services',
      'dns-svcs',
      'ngdc-network-ncs',
      'is-flow-log-collector',
      'sl-directlinkrequests',
      'sl-specialnetworkservices',
      'directlink',
      'directlink-connect',
      'directlink-dedicated',
      'ibm-cloud-load-balancer',
      'internet-svcs',
      'is',
      'oculus',
      'serviceendpoint',
      'transit-gateway',
      'ngdc-network-underlay-svc-endpoint',
      'iaas-network-subnet-rir'
    ]
  },
  {
    "platform": "platform-services",
    "serviceGroups": ["Compute - Development", "Network - Services", "Virtual Private Cloud - Undercloud", "VPC - Platform Services", "Compute - Operations", "Fabric", "Network - Underlay"],
    "email":"suparna@us.ibm.com",
    "services": [
      'iaas-fabric-classic',
      'iaas-fabric-ims-core',
      'iaas-fabric-ims-database',
      'iaas-fabric-ims-devauto',
      'iaas-fabric-ims-engine',
      'iaas-fabric-ims-identity',
      'iaas-fabric-op-auth',
      'iaas-fabric-op-cert',
      'iaas-fabric-op-dev-tools',
      'iaas-fabric-op-dns',
      'iaas-internal-systems',
      'is-continuous-deploy',
      'is-continuous-integration',
      'is-management-rack',
      'is-platform-integration',
      'is-ui',
      'is-vault',
      'is-vpc-infra',
      'ngdc-network-underlay',
      'ims-fabric',
      'ul-fabric',
      'ul-fabric-automation',
      'ul-fabric-bastion',
      'ul-fabric-inventory',
      'ul-fabric-kube',
      'ul-fabric-network',
      'ul-fabric-platform',
      'ul-fabric-virtualization',
      'is-flow-log-collector',
      'iaas-compute-general'
    ]
  },
  {
    "platform": "operations-and-compliance",
    "serviceGroups": ["IaaS Observability", "Virtual Private Cloud - Security Ops","ITOM-CMDB"],
    "email":"girishdhanak@in.ibm.com",
    "services": [
      'is-observability-dashboard',
      'is-observability-datalake',
      'is-observability-logging',
      'is-vpc',
      'is-vulnerability-scan',
      'content-ibm-sap-vpc-automation-bw4hana',
      'content-ibm-sap-vpc-automation-s4hana',
      'content-ibm-sap-vpc-automation-s4hana-sz-ha',
      'content-ibm-sap-vpc-automation-sapsingletierdb2',
      'content-ibm-terraform-ha-infra-3-tier-mzr',
      'content-ibm-terraform-ha-infra-3-tier-saz',
      'deploy-arch-ibm-hpc',
      'deploy-arch-ibm-sap-vpc-automation-hana-backup-cos',
      'deploy-arch-ibm-sap-vpc-automation-hana-nw-abap',
      'deploy-arch-ibm-sap-vpc-automation-hana-nw-abap-aas',
      'oss-itom'
    ]
  },
  {
    "platform": "data-center-operations",
    "serviceGroups": ["Data Center Operations"],
    "email":"jonathan.tuil@ibm.com",
    "services": [
      'iaas-cooling',
      'iaas-dc-facilities',
      'iaas-dc-hwsupport',
      'iaas-dc-security',
      'iaas-maintenance',
      'iaas-power',
      'sl-customer-portal'
    ]
  }
];

module.exports = { regionFromCrnMask, configNames, serviceGroupNames, vpMapping };
