[pytest]
markers =
    funct_incident_information: test incident information module
    funct_impacted_account: test impacted account module
    funct_incident_summary: test incident summary module
    funct_incident_log: test incident log module
    funct_similar_incident: test similar incident module
    funct_event_data: test event data module
    funct_summary_view: test summary view page module
    funct_alert_timeline: test alert timeline module
    funct_host_details: test host details module
    funct_change_request: test change request module
    funct_feedback: test feedback module
    funct_cbc: test caused by change module
    funct_related_incident: test related incident module
    funct_slack_warroom: test slack warroom module
    funct_alert_correlation: test alert correlation module
    funct_runbook: test runbook module
    funct_detailed_view_filter: test detailed view filter module
    funct_troubleshoot: test troubleshoot module
    funct_analytics_view_filter: test analytics view filter module
    funct_heat_map_cie: test heat map module
    smoke: quick test
log_format = %(asctime)s %(levelname)s %(module)s:%(filename)s:%(lineno)d %(message)s
log_date_format = %Y-%m-%dT%H:%M:%S
log_level = INFO
